### ISSUE TITLE
null pointer exception every time elevator is used.

### ISSUE THREAD

**Issue by steve4744** [InventivetalentDev/Elevators#9]
## What steps will reproduce the problem?  
1. Create a simple elevator in non-peaceful 1.14.4 world
2. Click the sign
3. Check the console

## What were you expecting to happen? What happened instead?  
The elevator seemingly works perfectly, but a NoSuchMethodException is logged to the console, followed by an NPE every time the elevator is used.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
2.1.1-SNAPSHOT

## What Spigot version are you using? *Type /version*  
1.14.4

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/Ny9z6PxY

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No, the elevator otherwise works normally

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No to Bungeecord. First time I've used the plugin.

**Comment by mvez73** [comment]
I have the exact same warning in console excepted my version of mincraft is 1.15.2 (paper)
https://pastebin.com/EzAKAi3F
